# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        
    - name: maven-settings-xml-action
      uses: whelk-io/maven-settings-xml-action@v18
      with:
        repositories: '[{ "id": "github", "url": "https://maven.pkg.github.com/TranscodeGroup/*" }]'
        servers: '[{ "id": "github", "username":"${{ secrets.GIT_USERNAME }}", "password": "${{ secrets.GIT_PASSWORD }}" }]'

    - name: checkout-action
      uses: actions/checkout@v2
    
    - name: Login to Registry 
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
            
    - name: Build with Maven
      run: mvn --batch-mode deploy -Dmaven.test.skip=true
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
